### ISSUE TITLE
itos.pkl

### ISSUE THREAD

**Issue by shef4793** [goru001/nlp-for-marathi#1]
![image](https://user-images.githubusercontent.com/14148218/62012079-229ad680-b19f-11e9-8f7b-586b3369c019.png)

![image](https://user-images.githubusercontent.com/14148218/62012096-760d2480-b19f-11e9-9be6-4d24ebf0adc5.png)

**Comment by goru001** [comment]
Hi @shef4793, thank you for reaching out. 

With fastai v1.0.50 and above (which is what i suppose you're using), the api for language_model_learner has been changed so you need to specify the architecture:
For eg:
learn = language_model_learner(data_lm, **AWD_LSTM**, drop_mult=0.3)
See cell no. 18 of [this](https://github.com/goru001/nlp-for-marathi/blob/master/language-model/Marathi_Language_Model.ipynb) notebook.

For the 1st error, because you're doing it on google colab and you don't have tmp folder prepopulated(which is done by fastai), do it the standard way by following along from cell no. 9 in [this notebook](https://github.com/goru001/nlp-for-marathi/blob/master/language-model/Marathi_Language_Model.ipynb). Just make sure your path is same as what google colab needs and you should be good!

I'm closing this issue as this is not a problem with the code, feel free to reach out if you're not able to get past these errors. Thanks!

**Comment by shef4793** [comment]
Alright! I'll try that...thanks
